import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextLink from "next/link";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const NavLink = ({
	href,
	children,
}: Readonly<{
	href: string;
	children: React.ReactNode;
}>) => (
	<NextLink href={href} className="text-white hover:underline">
		{children}
	</NextLink>
);

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="flex justify-center gap-8 p-4 absolute top-0 left-0 right-0">
					<NavLink href="/">Home</NavLink>
					<NavLink href="/one">Page 1</NavLink>
					<NavLink href="/two">Page 2</NavLink>
				</nav>

				<Suspense
					fallback={
						<div className="flex justify-center items-center min-h-screen w-full text-white">
							Loading...
						</div>
					}
				>
					{children}
				</Suspense>
			</body>
		</html>
	);
}
